services:
  app:
    build: . # when the repo is cloned and the Dockerfile is in the root
    # when using directly from the github hub
    # image: ghcr.io/fabalexsie/simple-web-upload-docker:master
    ports:
      - "1337:80"
      - "1338:443"
    volumes:
      - ./uploads:/var/www/html/uploads
      # this is just for testing purposes
      - ./src/index.php:/var/www/html/index.php
      - ./src/manifest.json:/var/www/html/manifest.json
    environment:
      - HOSTIP=192.168.0.113
